import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from '../components/NavBar'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tar Heel Dev Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NavBar />
        <div>
          <h1 className={styles.title}>
            Welcome to <a href="https://tarheeldevstudio">Tar Heel Dev Studio!</a>
          </h1>

          <p className={styles.description}>
           Growing your business by creating rich digital experiences that users can't resist. Let us help grow your business through web development, marketing, and graphic design. Get in touch or read our blog below!
          </p>
          <div className={styles.buttonDiv}>
           <a href="/contact" className={styles.contactBtn}>Get In Touch</a>
           <a href="/blog" className={styles.secondaryBtn}>Read Blog</a>
          </div>

        </div>

        <div className={styles.aboutSection}>
          <h3 className={styles.aboutTitle}>Authenticity, Creativity, and empathy are behind everything we do.</h3>
            <p className={styles.aboutDescription}>Have you ever been talking to a contractor or marketing team and felt like they didn't hear you? We won't ever let that happen here at Tar Heel Dev Studio, because the other guys suck and we rock!</p>

          <div className={styles.serviceSection}>
                <h2 className={styles.serviceTitle}>Services</h2>
                <h3 className={styles.serviceSub}>Check out any of our first class services below!</h3>
          </div>

             <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
               <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
               <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>

        </div>
        </div>


        <Footer />
      </main>


    </div>
  )
}
